version: '3'
volumes:
  data:
  styles:
  fonts:
  node_modules:


services:
  tileservergl:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7031:7021"
    restart: always
    volumes:
      # - ".:/app"
      - node_modules:/app/node_modules
      - data:/data
      - ./data:/data
      - styles:/app/node_modules/tileserver-gl-styles/styles
      - ./styles:/app/node_modules/tileserver-gl-styles/styles
      - fonts:/app/node_modules/tileserver-gl-styles/fonts
      # - ./fonts:/app/node_modules/tileserver-gl-styles/fonts