version: '3'
services:
  tileservergl:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      # - ".:/app"
      - "/app/node_modules"
      - ./data:/data
      - ./styles:/app/node_modules/tileserver-gl-styles/styles
      - ./fonts:/app/node_modules/tileserver-gl-styles/fonts
